# Generated by Django 4.1.1 on 2022-09-27 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'my_user',
            },
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
